# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - BootComMessaging

on:
  workflow_run:
    workflows: ["SonarCloud"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Replace Variables in appsettings.json
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\api\\\\appsettings.json"
          oldString: "{{LOGGING_CONNECTIONSTRING}}"
          newString: "${{secrets.LOGGING_CONNECTIONSTRING}}"
          showFileContent: true

      - name: Replace Variables in appsettings.json
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\api\\\\appsettings.json"
          oldString: "{{MESSAGING_CONNECTIONSTRING}}"
          newString: "${{secrets.MESSAGING_CONNECTIONSTRING}}"
          showFileContent: true

      - name: Replace Variables in appsettings.json
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\api\\\\appsettings.json"
          oldString: "{{MESSAGING_DATABASE_NAME}}"
          newString: "${{secrets.MESSAGING_DATABASE_NAME}}"
          showFileContent: true

      - name: Replace Variables in appsettings.json
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\api\\\\appsettings.json"
          oldString: "{{EMAIL_HOST}}"
          newString: "${{secrets.EMAIL_HOST}}"
          showFileContent: true

      - name: Replace Variables in appsettings.json
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\api\\\\appsettings.json"
          oldString: "{{EMAIL_PORT}}"
          newString: "${{secrets.EMAIL_PORT}}"
          showFileContent: true

      - name: Replace Variables in appsettings.json
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\api\\\\appsettings.json"
          oldString: "{{EMAIL_USE_SSL}}"
          newString: "${{secrets.EMAIL_USE_SSL}}"
          showFileContent: true

      - name: Replace Variables in appsettings.json
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\api\\\\appsettings.json"
          oldString: "{{FROM_EMAIL_ADDRESS}}"
          newString: "${{secrets.FROM_EMAIL_ADDRESS}}"
          showFileContent: true

      - name: Replace Variables in appsettings.json
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\api\\\\appsettings.json"
          oldString: "{{FROM_EMAIL_DISPLAY_NAME}}"
          newString: "${{secrets.FROM_EMAIL_DISPLAY_NAME}}"
          showFileContent: true

      - name: Replace Variables in appsettings.json
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\api\\\\appsettings.json"
          oldString: "{{FROM_EMAIL_USERNAME}}"
          newString: "${{secrets.FROM_EMAIL_USERNAME}}"
          showFileContent: true

      - name: Replace Variables in appsettings.json
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\api\\\\appsettings.json"
          oldString: "{{FROM_EMAIL_PASSWORD}}"
          newString: "${{secrets.FROM_EMAIL_PASSWORD}}"
          showFileContent: true

      - name: dotnet publish
        run: dotnet publish -c=Release -property:PublishDir=/publish --arch=x86

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: /publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C788F79EB5294B6092AC977685A89B17 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E246EDD782EB4B2C9D1C990C32BA09C7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7462CBD8901A431186C108E5F1F6E2AD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BootComMessaging'
          slot-name: 'Production'
          package: .

          





