# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - BootComMessaging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Replace Variables in appsettings.json
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\api\\\\appsettings.json"
          oldString: "{{LOGGING_CONNECTIONSTRING}}"
          newString: "${{secrets.LOGGING_CONNECTIONSTRING}}"
          showFileContent: true

      - name: Replace Variables in appsettings.json
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\api\\\\appsettings.json"
          oldString: "{{MESSAGING_CONNECTIONSTRING}}"
          newString: "${{secrets.MESSAGING_CONNECTIONSTRING}}"
          showFileContent: true

      - name: Replace Variables in appsettings.json
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\api\\\\appsettings.json"
          oldString: "{{MESSAGING_DATABASE_NAME}}"
          newString: "${{secrets.MESSAGING_DATABASE_NAME}}"
          showFileContent: true

      - name: Replace Variables in appsettings.json
        uses: Nambers/ReplaceStringInFile@v1.3
        with:
          path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\api\\\\appsettings.json"
          oldString: "{{MESSAGING_EMAIL_API_KEY}}"
          newString: "${{secrets.MESSAGING_EMAIL_API_KEY}}"
          showFileContent: true

      - name: dotnet publish
        run: dotnet publish -c=Release -property:PublishDir=/publish --arch=x86

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: /publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A5EB16263A4B4075A935E1E6A953E008 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_28F7E5CC404C4DA380D629D011D24945 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BE33B4FA56AC4E2ABFE6ADE3705ECA70 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BootComMessaging'
          slot-name: 'Production'
          package: .
          
