name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # Adjust to the version you're using

    - name: Replace Variables in appsettings.json
      uses: Nambers/ReplaceStringInFile@v1.3
      with:
        path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\API\\\\appsettings.json"
        oldString: "{{MESSAGING_CONNECTIONSTRING}}"
        newString: "${{secrets.MESSAGING_CONNECTIONSTRING}}"
        showFileContent: true

    - name: Replace Variables in appsettings.json
      uses: Nambers/ReplaceStringInFile@v1.3
      with:
        path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\API\\\\appsettings.json"
        oldString: "{{MESSAGING_DATABASE_NAME}}"
        newString: "${{secrets.MESSAGING_DATABASE_NAME}}"
        showFileContent: true

    - name: Replace Variables in appsettings.json
      uses: Nambers/ReplaceStringInFile@v1.3
      with:
        path: "D:\\\\a\\\\messaging-api\\\\messaging-api\\\\API\\\\appsettings.json"
        oldString: "{{LOGGING_CONNECTIONSTRING}}"
        newString: "${{secrets.LOGGING_CONNECTIONSTRING}}"
        showFileContent: true

    # Run dotnet build and publish
    - name: dotnet build and publish
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release --property:PublishDir='publish'

    - name: Azure login
      uses: azure/login@v2
      with:
         creds: ${{ secrets.AZURE_APP_SERVICE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: "BootComMessaging"
    
    - name: logout
      run: |
          az logout
